"""Add age and gender to users

Revision ID: 1b04f8a6f3c5
Revises: 5e742175dbbf
Create Date: 2025-07-15 08:02:08.963160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b04f8a6f3c5'
down_revision = '5e742175dbbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
