"""あなたの変更内容を説明するメッセージ

Revision ID: 52b108adb177
Revises: 590816e5f786
Create Date: 2025-07-22 05:51:46.874934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52b108adb177'
down_revision = '590816e5f786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('preferred', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('preferred')
        batch_op.drop_column('available')

    # ### end Alembic commands ###
