"""Initial migration

Revision ID: 5e742175dbbf
Revises: 
Create Date: 2025-06-18 17:42:57.724215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e742175dbbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferred_style', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('season', sa.String(length=255), nullable=True),
    sa.Column('is_formal', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personal_color', sa.String(length=255), nullable=True),
    sa.Column('body_shape', sa.String(length=255), nullable=True),
    sa.Column('disliked_colors', sa.String(length=255), nullable=True),
    sa.Column('disliked_styles', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('outfit_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('suggested_date', sa.Date(), nullable=False),
    sa.Column('top_id', sa.Integer(), nullable=True),
    sa.Column('bottom_id', sa.Integer(), nullable=True),
    sa.Column('outer_id', sa.Integer(), nullable=True),
    sa.Column('weather_info', sa.String(length=255), nullable=True),
    sa.Column('occasion_info', sa.String(length=255), nullable=True),
    sa.Column('suggested_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bottom_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['outer_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['top_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_suggestions')
    op.drop_table('user_preferences')
    op.drop_table('clothes')
    op.drop_table('users')
    # ### end Alembic commands ###
